/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.persistence.Combo;
import com.mycompany.persistence.ComboDAO;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conve
 */
public class ComboMain extends javax.swing.JFrame {

    /**
     * Creates new form ComboMain
     */
    public ComboMain() {
        initComponents();
        loadTable();
    }
    
    public void loadTable(){
        
        ComboDAO comboDAO = new ComboDAO();
        List<Combo> combos = comboDAO.list();
        fillTable(combos);
    
    }
   
    private void fillTable(List<Combo> combos){
        String columns[] ={"Id", "Nome", "Preço"};
        String data[][] = new String[combos.size()][columns.length];
        
        int i =0;
        for(Combo c : combos){
            data[i] = new String[]{
                String.valueOf(c.getId()),
            c.getName(),
            String.valueOf(c.getPrice())
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(data,columns);
        jTCombo.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCombo = new javax.swing.JTable();
        jBCreate = new javax.swing.JButton();
        jBEUpdate = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBReturn = new javax.swing.JButton();
        jBReady = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Combo");

        jTCombo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCombo);

        jBCreate.setText("Criar");
        jBCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateActionPerformed(evt);
            }
        });

        jBEUpdate.setText("Editar Preço");
        jBEUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEUpdateActionPerformed(evt);
            }
        });

        jBDelete.setText("Excluir");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBReturn.setText("Voltar");
        jBReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReturnActionPerformed(evt);
            }
        });

        jBReady.setText("Ler Combo");
        jBReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReadyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jBEUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jBCreate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBReady)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jBReady)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCreate)
                    .addComponent(jBEUpdate)
                    .addComponent(jBDelete)
                    .addComponent(jBReturn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jBReturnActionPerformed

    private void jBCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateActionPerformed
        ComboRegistration comboRegistration = new ComboRegistration(this);
        comboRegistration.setVisible(true);
    }//GEN-LAST:event_jBCreateActionPerformed
        // Um zoom para ver quais itens fazem parte do combo
    private void jBReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReadyActionPerformed
        
        try {
        int selectedRow = jTCombo.getSelectedRow();
        if (selectedRow >= 0) {

            int comboId = Integer.parseInt(String.valueOf(jTCombo.getValueAt(selectedRow, 0)));

            ComboRead comboRead = new ComboRead(this, comboId);
            comboRead.setLocationRelativeTo(this);
            comboRead.setVisible(true);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro. Não foi possível ler o combo");
    }

        
    }//GEN-LAST:event_jBReadyActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        
        try{
            
            int selectedRow = jTCombo.getSelectedRow();
            
            if(selectedRow>=0){
                int id = Integer.parseInt(String.valueOf(jTCombo.getValueAt(selectedRow, 0)));
                
                String name =String.valueOf(jTCombo.getValueAt(selectedRow, 1));
                
                int response = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o combo "+ name+"?");
                
                if(response==JOptionPane.YES_OPTION){
                    ComboDAO comboDAO = new ComboDAO();
                    Combo combo = comboDAO.select(id);
                    
                    if(combo ==null){
                         JOptionPane.showMessageDialog(this, "Combo não encontrado.");
                        return;
                    
                    }

                    
                    comboDAO.delete(combo);
                    JOptionPane.showMessageDialog(this, "Combo deletado com sucesso");
                }
            }else{JOptionPane.showMessageDialog(this, "Combo não encontrado");}
            loadTable();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao excluir combo");
        }
        
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBEUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEUpdateActionPerformed
        
        
        try{
            ComboUpdate comboUpdate = new ComboUpdate(this);
            String id = (String) jTCombo.getValueAt(jTCombo.getSelectedRow(), 0);
            
            ComboDAO comboDAO = new ComboDAO();
            
            Combo selectedCombo = comboDAO.select(Integer.parseInt(id));
            
            comboUpdate.fillUpdate(selectedCombo);
            comboUpdate.setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro.");
        }
            
    }//GEN-LAST:event_jBEUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCreate;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBEUpdate;
    private javax.swing.JButton jBReady;
    private javax.swing.JButton jBReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCombo;
    // End of variables declaration//GEN-END:variables
}
