/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.model.ComboItemTemp;
import com.mycompany.persistence.Combo;
import com.mycompany.persistence.ComboDAO;
import com.mycompany.persistence.ComboItem;
import com.mycompany.persistence.ComboItemDAO;
import com.mycompany.persistence.ComboItemId;
import com.mycompany.persistence.Product;
import com.mycompany.persistence.ProductDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conve
 */
public class ComboItemInsert extends javax.swing.JFrame {
    
    private Combo combo;
    private ComboRegistration parent;
    private List<ComboItemTemp> comboList = new ArrayList<>();
    
    public ComboItemInsert(ComboRegistration parent, Combo combo) {
        this.parent = parent;
        this.combo = combo;
        initComponents();
        loadProductTable();
    }
    
    public void loadProductTable(){
        ProductDAO productDAO = new ProductDAO();
        List<Product> products = productDAO.list();
        fillTable(products);
    }
    
    private void fillTable(List<Product> products){
        String columns[]= {"Id", "Nome", "Tipo", "Tamanho", "Preço un", "Custo un"};
        String data [][] = new String[products.size()][columns.length];
        
        int i =0;
        
        for(Product p : products){
            data[i] = new String[]{
                String.valueOf(p.getId()),
                p.getProductName(),
                String.valueOf(p.getProductType()),
                String.valueOf(p.getSize()),
                
                String.valueOf(p.getUnitPrice()),
                String.valueOf(p.getUnitCost())


                
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(data,columns);
        jTProduct.setModel(model);
       
    }
    
    private void updateComboTable(){
        String[] columns= {
        "Produto", "Tipo", "Tamanho","Qt", "Preço un"
        };
        String[][] data = new String[comboList.size()][columns.length];
        
        int i =0;
        for(ComboItemTemp item : comboList){
            data[i] = new String[]{
            item.getProduct().getProductName(),
                String.valueOf(item.getProduct().getProductType()),
                String.valueOf(item.getProduct().getSize()),
                String.valueOf(item.getQuantity()),
                String.valueOf(item.getProduct().getUnitPrice())
            
            
            };i++;
        }
        DefaultTableModel comboModel = new DefaultTableModel(data,columns);
        jTComboItems.setModel(comboModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProduct = new javax.swing.JTable();
        jBAdd = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        jBReturn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jS = new javax.swing.JScrollPane();
        jTComboItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Itens do Combo");

        jTProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProduct);

        jBAdd.setText("Adicionar");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jBSave.setText("Salvar");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBReturn.setText("Voltar");
        jBReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAdd)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBReturn)
                        .addGap(18, 18, 18)
                        .addComponent(jBSave)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jBAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave)
                    .addComponent(jBReturn))
                .addGap(16, 16, 16))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Combo");

        jTComboItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jS.setViewportView(jTComboItems);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jS, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jS, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jBReturnActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        
        try{
            int selectedRow = jTProduct.getSelectedRow();
            if(selectedRow>=0){
                int productId = Integer.parseInt(String.valueOf(jTProduct.getValueAt(selectedRow, 0)));
                
                ProductDAO productDAO = new ProductDAO();
                Product product = productDAO.select(productId);
                
                if(product == null){
                    JOptionPane.showMessageDialog(this, "Item não encontrado");
                    return;
                }
                
                boolean found = false; //Caso não tenha o tipo de item na lista = false
                                       // Caso tenha = true
                
                for(ComboItemTemp item : comboList){
                    if(item.getProduct().getId() ==productId){
                        item.increment();
                        found = true;
                        break;
                    }
                }
                if(!found){
                comboList.add(new ComboItemTemp(product));}
                updateComboTable();
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao Adicionar item no combo");
        }
        
        
    }//GEN-LAST:event_jBAddActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        if(comboList.isEmpty()){
            JOptionPane.showMessageDialog(this, "Combo vazio.\nAdicione algum item.");
            return;
        }
        try{
            ComboDAO comboDAO = new ComboDAO();
            ComboItemDAO comboItemDAO = new ComboItemDAO();
            
            comboDAO.register(combo);//registrar o id do combo
            
            for (ComboItemTemp i : comboList) {

                ComboItem item = new ComboItem();

                ComboItemId id = new ComboItemId(
                    combo.getId(),
                    i.getProduct().getId()
                );

                item.setId(id);
                item.setCombo(combo);
                item.setProduct(i.getProduct());
                item.setQuantity(i.getQuantity());

                comboItemDAO.register(item);
            }

            JOptionPane.showMessageDialog(this, "Combo Salvo com sucesso");
            parent.loadMaster();
            parent.dispose();
            dispose();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao salvar combo");
            
        
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBReturn;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTComboItems;
    private javax.swing.JTable jTProduct;
    // End of variables declaration//GEN-END:variables
}
