/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.persistence.ComboItem;
import com.mycompany.persistence.ComboItemDAO;
import com.mycompany.persistence.Product;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conve
 */
public class ComboRead extends javax.swing.JFrame {

    private ComboMain master;
    private int comboId;
    
    public ComboRead(ComboMain master, int comboId) {
        this.master = master;
        this.comboId = comboId;
        initComponents();
        loadTable();
    }
    
    /*
    private Product productUpdate = null;
    public void fillUpdate(Product p){
        jTFName.setText(p.getProductName());
        jCBType.setSelectedItem(p.getProductType());
        jCBSize.setSelectedItem(p.getSize());
        jTFQuantity.setText(String.valueOf(p.getQuantityInStock()));
        jTFPrice.setText(String.valueOf(p.getUnitPrice()));
        jTFCost.setText(String.valueOf(p.getUnitCost()));
        productUpdate = p;
        
    }
    */
    
    
    private void loadTable() {
        
    ComboItemDAO comboItemDAO = new ComboItemDAO();
    List<ComboItem> items = comboItemDAO.ListItems(comboId);
    fillTable(items);

    }
    
    private void fillTable(List<ComboItem> items){
        String columns[]= {"Id", "Nome", "Tipo", "Tamanho","Quantidade", "Preço", "Custo"};
        String data [][] = new String[items.size()][columns.length];
        
        int i =0;
        
        for(ComboItem ci : items){
            Product p = ci.getProduct();
            double cost = ci.getQuantity() * p.getUnitCost();
            double price = ci.getQuantity() * p.getUnitPrice();
            data[i] = new String[]{
                String.valueOf(p.getId()),
                p.getProductName(),
                String.valueOf(p.getProductType()),
                String.valueOf(p.getSize()),
                String.valueOf(ci.getQuantity()),
                String.valueOf(p.getUnitPrice()),
                
                String.valueOf(price),
                String.valueOf(cost)


                
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(data,columns);
        jTComboZoom.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTComboZoom = new javax.swing.JTable();
        jBReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTComboZoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTComboZoom);

        jBReturn.setText("Voltar");
        jBReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBReturn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBReturn)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jBReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTComboZoom;
    // End of variables declaration//GEN-END:variables
}
