/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.persistence.Screening;
import com.mycompany.persistence.ScreeningDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conve
 */
public class ScreeningMain extends javax.swing.JFrame {
private boolean filter;
public boolean isFilter() {
    return filter;
}
    public ScreeningMain() {
        initComponents();
        
        loadTable(false);
    }
    
    
   public void loadTable(boolean filter){
   
       ScreeningDAO screeningDAO = new ScreeningDAO();
       List<Screening> screenings = screeningDAO.list(filter);
       fillTable(screenings);
   }
    
    private void fillTable(List<Screening> screenings){
        String columns[] = {"Id","Nome", "Começo", "Fim"};
        String data[][] = new String[screenings.size()][columns.length];
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        int i =0;
        for(Screening s: screenings){
            data[i] = new String[]{
            
            String.valueOf(s.getId()),
                s.getMovie().getName(),
                String.valueOf(s.getStart().format(dtf)),
                String.valueOf(s.getEnd().format(dtf))
            };
            i++;
        
        }
        
        DefaultTableModel model = new DefaultTableModel(data, columns);
        jTScreening.setModel(model);
       
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTScreening = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jCBFilter = new javax.swing.JComboBox<>();
        jBEdit = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBReturn = new javax.swing.JButton();
        jBCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sessões");

        jTScreening.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTScreening);

        jLabel2.setText("Sessões:");

        jCBFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "A exibir" }));
        jCBFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFilterActionPerformed(evt);
            }
        });

        jBEdit.setText("Editar");
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        jBDelete.setText("Excluir");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBReturn.setText("Voltar");
        jBReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReturnActionPerformed(evt);
            }
        });

        jBCreate.setText("Criar Sessão");
        jBCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jBEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jBCreate)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEdit)
                    .addComponent(jBDelete)
                    .addComponent(jBReturn)
                    .addComponent(jBCreate))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFilterActionPerformed
        if("A exibir".equals(String.valueOf(jCBFilter.getSelectedItem()))){
            filter = true;
        }else{
            filter = false;}

        loadTable(filter);

    }//GEN-LAST:event_jCBFilterActionPerformed

    private void jBReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReturnActionPerformed
        dispose();
    }//GEN-LAST:event_jBReturnActionPerformed

    private void jBCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateActionPerformed
        ScreeningRegistration screeningRegistration = new ScreeningRegistration(this); //this, por conta do constructor
        screeningRegistration.setVisible(true);
       
    }//GEN-LAST:event_jBCreateActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        //jCBFilterActionPerformed(evt)
        try{
            int selectedRow = jTScreening.getSelectedRow();
            if(selectedRow>=0){
                int id = Integer.parseInt(String.valueOf(jTScreening.getValueAt(selectedRow, 0)));
            
            
            
            int response = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o item "+id+"?");
            //yes=0, no =1, cancel=2
            if(response == JOptionPane.YES_OPTION){//0
                ScreeningDAO screeningDAO = new ScreeningDAO();
                Screening screening = screeningDAO.select(id);
                
                if(screening == null){
                    JOptionPane.showMessageDialog(this, "Produto não encontrado.");
                    return;
                }
                screeningDAO.delete(screening);
                    JOptionPane.showMessageDialog(this, "Produto deletado com sucesso");
                }
                }else{
                JOptionPane.showMessageDialog(this, "Produt não encontrado");
                }
            jCBFilterActionPerformed(evt);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro.\nNão foi possível deletar o item");
        
        }
        
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
        try{
            //Preenchendo na parte de edição os dados selecionados
            ScreeningRegistration screeningRegistration = new ScreeningRegistration(this);//Criar um parente para atualizar a lista automaticamente após a edição
            String id =(String)jTScreening.getValueAt(jTScreening.getSelectedRow(), 0);
            
            ScreeningDAO screeningDAO = new ScreeningDAO();
            
            Screening selectedScreening = screeningDAO.select(Integer.parseInt(id));
            
            screeningRegistration.fillUpdate(selectedScreening);
            screeningRegistration.setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Ocorre uma falha.");
            
        }
        
        
    }//GEN-LAST:event_jBEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreeningMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreeningMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreeningMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreeningMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreeningMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCreate;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBEdit;
    private javax.swing.JButton jBReturn;
    private javax.swing.JComboBox<String> jCBFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTScreening;
    // End of variables declaration//GEN-END:variables
}
